controller_joint_names: ['', 'Joint01_FL', 'Joint02_FL', 'Joint03_FL', 'Joint01_FR', 'Joint02_FR', 'Joint03_FR', 'Joint01_BL', 'Joint02_BL', 'Joint03_BL', 'Joint01_BR', 'Joint02_BR', 'Joint03_BR', ]
