robot_name: 'anymal_d'

joint_names: &jn ["LF_HAA", "LF_HFE", "LF_KFE", "LH_HAA", "LH_HFE", "LH_KFE", "RF_HAA", "RF_HFE", "RF_KFE", "RH_HAA", "RH_HFE", "RH_KFE"]
base_name: "base"

state_topic: "anymal_d/state"
command_topic: "anymal_d/command"
change_controller_topic: "anymal_d/change_controller"
contact_topics: ["/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact","/rh_foot_contact"] 


state_publisher:
  update_rate: 400 # Hz

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.4, -0.8, 0.0, -0.4, 0.8, 0.0, 0.4, -0.8, 0.0, -0.4, 0.8] # LF, LH, RF, RH
  sit_controller:
    joint_angles: [0.0, 1.5, -2.6, 0.0, -1.5, 2.6, 0.0, 1.5, -2.6, 0.0, -1.5, 2.6] # LF, LH, RF, RH
  kp: 400
  kd: 5
  interpolation_time: 1.0 # s
  rate: 50 # Hz

mpc_controller:
  wbc_type: "sqp"
  reference_trajectory:
    terrain_topic: "/convex_plane_decomposition_ros/filtered_map"
    reference_topic: "/anymal_mpc_target"
    observation_topic: "/anymal_mpc_observation"
    traj_dt: 0.1
    traj_knots: 10
    blind: true

anymal_d:
  joint_controller:
      type: tbai_gazebo/JointController
      joints: *jn

reference_generator:
  type: "joystick"

  joystick:
    topic: "joy"
    ramped_velocity: 5.0
    x_index: 1
    y_index: 0
    yaw_index: 3
    x_scale: 1.0
    y_scale: 0.5
    yaw_scale: 0.5

  twist:
    topic: "cmd_vel"

contact_sensor:
  update_rate: 20 # Hz